baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Today I Learned'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about/about"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pageRef = "/posts"
    weight = 20

  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    pageRef = "/notes"
    weight = 30

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    pageRef = "/projects"
    weight = 40

  [[menu.main]]
    identifier = "graph"
    name = "Graph"
    pageRef = "/graph"
    weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
